version: '3.8'

services:
#  api:
#    env_file: ".env"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "${API_PORT:-8080}:8080"
#    volumes:
#      - .:/app
#    depends_on:
#      - postgres
#      - redis
#    environment:
#      - DB_HOST=${DB_HOST:-localhost}
#      - DB_PORT=${DB_PORT:-5432}
#      - DB_USER=${DB_USER:-postgres}
#      - DB_PASSWORD=${DB_PASSWORD:-postgres}
#      - DB_NAME=${DB_NAME:-postgres}
#      - REDIS_HOST=${REDIS_HOST:-localhost}
#      - REDIS_PORT=${REDIS_PORT:-6379}
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - WEATHER_API_KEY=${WEATHER_API_KEY}
#    restart: unless-stopped

  postgres:
    env_file: ".env"    
    image: postgres:14-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_DB:-postgres}
    restart: unless-stopped

  redis:
    env_file: ".env"
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
