version: '3.8'

services:
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "${API_PORT}:8080"
#    volumes:
#      - .:/app
#    depends_on:
#      - postgres
#      - redis
#    environment:
#      - DB_HOST=${DB_HOST}
#      - DB_PORT=${DB_PORT}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_NAME=${DB_NAME}
#      - REDIS_HOST=${REDIS_HOST}
#      - REDIS_PORT=${REDIS_PORT}
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - WEATHER_API_KEY=${WEATHER_API_KEY}
#    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
